# Generated by Django 4.1.4 on 2022-12-29 15:12

import django.core.validators
from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='stars',
            field=models.PositiveSmallIntegerField(default=True, validators=[main_page.models.Response.validate_even]),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone_num',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Некоректно введено номер телефону.', regex='(^\\+380)(-|\\s)?(\\d{2})(-|\\s)?(\\d{3})(-|\\s)?(\\d{2})(-|\\s)?(\\d{2})')]),
        ),
    ]
