# Generated by Django 4.1.4 on 2023-01-17 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_response_stars_alter_about_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('name_city', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Некоректно введено номер телефону.', regex='(^\\+380)(-|\\s)?(\\d{2})(-|\\s)?(\\d{3})(-|\\s)?(\\d{2})(-|\\s)?(\\d{2})')])),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Некоректно введено пошту.', regex='^[a-zA-Z0-9](-?[a-zA-Z0-9_])+@[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)*$')])),
                ('work_time', models.CharField(max_length=100)),
                ('close_time', models.CharField(max_length=100)),
            ],
        ),
    ]
