# Generated by Django 4.1.7 on 2023-08-05 07:41

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='back_img',
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to=main_page.models.get_file_name7),
        ),
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.get_file_name4),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.get_file_name1),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.get_file_name2),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.get_file_name3),
        ),
        migrations.AlterField(
            model_name='response',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.get_file_name5),
        ),
    ]
