# Generated by Django 4.1.4 on 2022-12-30 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_people', models.SmallIntegerField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Некоректно введено номер телефону.', regex='(^\\+38)?(-|\\s)?(\\d{3})(-|\\s)?(\\d{3})(-|\\s)?(\\d{2})(-|\\s)?(\\d{2})')])),
                ('message', models.TextField(blank=True, max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('data_in', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-data_in',),
            },
        ),
    ]
